apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - ./deployment-patch.yml

images:
- name: cicd-web-project
  newTag: newest
  newName: eu.gcr.io/my-project/postgres

resources:
- ../../base-kustomize
